[workspace]
resolver = "2"
members = [
    "packages/applications/arithmico", 
    "packages/applications/create_version", 
    "packages/applications/cssbundler",
    "packages/libraries/*"
]

[workspace.dependencies]
thiserror = "2.0.18"
nom = "8.0.0"
serde = { version = "1.0.228", features = ["derive"] }
leptos = { version = "0.8.17", features = ["csr"] }
leptos_dom = { version = "0.8.7" }
