[workspace]
resolver = "2"
members = [
    "packages/applications/arithmico", 
    "packages/applications/create_version", 
    "packages/libraries/*",
]

[workspace.dependencies]
thiserror = "2.0.18"
serde = { version = "1.0.228", features = ["derive"] }
leptos = { version = "0.8.19", features = ["csr"] }
leptos_dom = { version = "0.8.7" }
