[navigation.calculator]
English = "Calculator"
German = "Rechner"

[navigation.settings]
English = "Settings"
German = "Einstellungen"

[navigation.reference]
English = "Reference"
German = "Referenz"

[navigation.about]
English = "About"
German = "Über"

[calculator.title]
English = "Calculator"
German = "Rechner"

[calculator.error.description]
English = "Description"
German = "Beschreibung"

[calculator.error.error_kind]
English = "Error Kind"
German = "Fehlertyp"

[calculator.evaluate_node_error]
English = "Evaluation Error"
German = "Auswertungsfehler"

[calculator.toolbar.actions]
English = "Actions"
German = "Aktionen"

[calculator.toolbar.definitions]
English = "Definitions"
German = "Definitionen"

[calculator.toolbar.history]
English = "History"
German = "Verlauf"

[settings.title]
English = "Settings"
German = "Einstellungen"

[settings.section.general]
English = "Genral"
German = "Allgemein"

[settings.section.calculator]
English = "Calculator"
German = "Rechner"

[settings.language]
English = "Language"
German = "Sprache"

[settings.language.german]
English = "German"
German = "Deutsch"

[settings.language.english]
English = "English"
German = "Englisch"

[settings.override_decimal_format]
English = "Override decimal format"
German = "Dezimalformat überschreiben"

[settings.override_decimal_format.no]
English = "No"
German = "Nein"

[settings.decimal_places]
English = "Decimal places"
German = "Dezimalstellen"

[settings.theme]
English = "Color Theme"
German = "Farbschma"

[settings.theme.light]
English = "Light"
German = "Hell"

[settings.theme.dark]
English = "Dark"
German = "Dunkel"

[reference.title]
English = "Reference"
German = "Referenz"

[reference.search]
English = "Search"
German = "Suche"

[about.title]
English = "About"
German = "Über"

[not-found.title]
English = "Page Not Found"
German = "Seite nicht gefunden"

[not-found.description]
English = "The page you are looking for might have been moved, deleted, or never existed. Try going back to the homepage."
German = "Die Seite, die Sie suchen, wurde möglicherweise verschoben oder gelöscht. Versuchen Sie, zur Startseite zurückzukehren."

[calculator.toolbar.actions.clear-input]
English = "Clear Input"
German = "Eingabe löschen"

[calculator.toolbar.actions.clear-output]
English = "Clear Output"
German = "Ausgabe löschen"

[calculator.toolbar.actions.reset-session]
English = "Reset Session"
German = "Sitzung zurücksetzen"