[navigation.calculator]
English = "Calculator"
German = "Rechner"

[navigation.settings]
English = "Settings"
German = "Einstellungen"

[navigation.reference]
English = "Reference"
German = "Referenz"

[navigation.about]
English = "About"
German = "Über"

[calculator.title]
English = "Calculator"
German = "Rechner"

[calculator.error.description]
English = "Description"
German = "Beschreibung"

[calculator.error.error_kind]
English = "Error Kind"
German = "Fehlertyp"

[calculator.evaluate_node_error]
English = "Evaluation Error"
German = "Auswertungsfehler"

[settings.title]
English = "Settings"
German = "Einstellungen"

[settings.language]
English = "Language"
German = "Sprache"

[settings.language.german]
English = "German"
German = "Deutsch"

[settings.language.english]
English = "English"
German = "Englisch"

[settings.override_decimal_format]
English = "Override decimal format"
German = "Dezimalformat überschreiben"

[settings.override_decimal_format.no]
English = "No"
German = "Nein"

[settings.theme]
English = "Color Theme"
German = "Farbschma"

[settings.theme.light]
English = "Light"
German = "Dark"

[settings.theme.dark]
English = "Dark"
German = "Dunkel"

[reference.title]
English = "Reference"
German = "Referenz"

[about.title]
English = "About"
German = "Über"