[watch]
watch = ["../../"]
ignore = ["./index.css"]

[build]
target = "index.html"
dist = "dist"
minify = "on_release"

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = [
    "-c", 
    'find ../../.. -type f -name "*.css" ! -path "*/dist/*" ! -name "index.css" -exec cat {} + > index.css'
]
