[error.number.closed_interval]
English = "Parameter value has to be in the closed interval between {min} and {max}."
German = "Parameterwert muss im geschlossenem Intervall zwischen {min} und {max} liegen."

[error.number.open_interval]
English = "Parameter value has to be in the open interval between {min} and {max}."
German = "Parameterwert muss im offenen Intervall zwischen {min} und {max} liegen."

[error.number.integer]
English = "{value} is not an integer."
German = "{value} ist keine Ganzzahl."

[error.number.less_than]
English = "{value} is not less than {v}."
German = "{value} ist nicht kleiner als {v}."

[error.number.less_than_or_equal]
English = "{value} is not less than or equal to {v}."
German = "{value} ist nicht kleiner oder gleich {v}."

[error.number.greater_than]
English = "{value} is not greater than {v}."
German = "{value} ist nicht größer als {v}."

[error.number.greater_than_or_equal]
English = "{value} is not greater than or equal to {v}."
German = "{value} ist nicht größer oder gleich {v}."

[error.number.equal]
English = "{value} is not equal to {v}."
German = "{value} ist nicht gleich {v}."

[error.number.not_equal]
English = "Value must be not equal to {v}."
German = "Wert darf nicht gleich {v} sein."

[error.tensor.not_empty]
English = "Tensor must not be empty."
German = "Der Tensor darf nicht leer sein."

[error.tensor.rank]
English = "Expected a tensor of rank {expected}, but received rank {actual}."
German = "Der Rang des Tensors sollte {expected} sein, beträgt aber tatsächlich {actual}."

[error.tensor.shape]
English = "Expected tensor dimensions {expected}, but got {actual}."
German = "Die Dimensionen des Tensors sollten {expected} sein, sind aber tatsächlich {actual}."

[error.tensor.equal_shape]
English = "Expected tensors to have equal dimensions, but got dimensions {left} and {right}."
German = "Erwartet wurden Tensoren mit identischen Dimensionen, stattdessen haben sie die Dimensionen {left} und {right}."

[error.tensor.vector_dimension]
English = "The vector is expected to have exactly {dim} elements."
German = "Der Vektor muss genau {dim} Elemente haben."

[error.tensor.vector_min_dimension]
English = "The vector is expected to have at least {dim} elements."
German = "Der Vektor muss mindestens {dim} Elemente haben."


[error.node.too_few_variables]
English = "The expression contains too few unknown variables. Expected {expected}, but found {actual}."
German = "Der Ausdruck enthält zu wenige unbekannte Variablen. Erwartet wurden {expected}, gefunden wurden {actual}."

[error.node.too_many_variables]
English = "The expression contains too many unknown variables. Expected {expected}, but found {actual}."
German = "Der Ausdruck enthält zu viele unbekannte Variablen. Erwartet wurden {expected}, gefunden wurden {actual}."

[error.node.invalid_variable_name]
English = "Invalid variable name. Expected {expected}, but found {actual}."
German = "Ungültiger Variablenname. Statt {expected} wurde {actual} vorgefunden."

[error.function.too_few_arguments]
English = "The function has too few arguments. Expected {expected}, but found {actual}."
German = "Die Funktion hat zu wenige Argumente. Erwartet wurden {expected}, gefunden wurden {actual}."

[error.function.too_many_arguments]
English = "The function has too many arguments. Expected {expected}, but found {actual}."
German = "Die Funktion hat zu viele Argumente. Erwartet wurden {expected}, gefunden wurden {actual}."

[error.function.argument_symbol_mismatch]
English = "The function argument \"{argument}\" does not match the unknown variable \"{symbol}\"."
German = "Das Funktionsargument \"{argument}\" stimmt nicht mit der unbekannten Variable \"{symbol}\" überein."
