name: Check Pull Request
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo test --all-features
        shell: bash

  test-e2e:
    name: Run E2E Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: cargo-bins/cargo-binstall@main
    - name: Setup toolchain
      shell: bash
      run: |
        rustup target add wasm32-unknown-unknown
        cargo binstall -y --locked trunk
        cargo install cssbundler --path packages/applications/cssbundler
    - uses: actions/setup-node@v6
      with:
        node-version: 22
    - name: Install NPM Dependencies
      run: npm ci
    - name: Install Playwright
      run: npx playwright install --with-deps
    
    - name: Prebuild App
      working-directory: packages/applications/arithmico
      shell: bash
      run: |
        touch index.css 
        ~/.cargo/bin/trunk build
     
    - name: Run E2E Tests
      working-directory: packages/applications/arithmico-e2e
      run: npx playwright test

  build-review-artifact:
    name: Build Review Artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: cargo-bins/cargo-binstall@main
    - name: Setup toolchain
      shell: bash
      run: |
        rustup target add wasm32-unknown-unknown
        cargo binstall -y --locked trunk
        cargo install cssbundler --path packages/applications/cssbundler
    - name: Build Artifact
      working-directory: packages/applications/arithmico
      shell: bash
      env:
        APP_VERSION: review-${{ github.event.number }}
      run: |
        touch index.css 
        ~/.cargo/bin/trunk build --release
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@6.2.2
      with:
        role-to-assume: ${{ secrets.CDK_ROLE_ARN }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ vars.AWS_REGION }}
    - name: Upload Artifact
      working-directory: packages/applications/arithmico/dist
      shell: bash
      env:
        BUCKET_NAME: ${{ vars.ARTIFACTS_BUCKET_NAME }}
        PR_NUMBER: ${{ github.event.number }}
      run:
        ARTIFACT="review-$PR_NUMBER";
        DEST_PATH="s3://$BUCKET_NAME/calculator/$ARTIFACT/main/web";
        aws s3 sync . $DEST_PATH --delete;

  deploy-review-environment:
    name: Deploy Review Environment
    runs-on: ubuntu-latest
    needs: 
      - build-review-artifact
    concurrency:
      group: review-environment-${{ github.event.number }}
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@6.2.2
      with:
        role-to-assume: ${{ secrets.CDK_ROLE_ARN }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ vars.AWS_REGION }}
    - name: Install NPM Dependencies
      run: npm ci
    - name: CDK Deploy
      working-directory: infrastructure
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: ${{ vars.AWS_REGION }}
        CDK_DEPLOY_ARTIFACT: review-${{ github.event.number }}
        CDK_DEPLOY_ENVIRONMENT: review-${{ github.event.number }}
      run: npm run cdk -- deploy --all --require-approval never
    - name: Create Cloudfront Invalidation
      shell: bash
      env:
        CDK_DEPLOY_ENVIRONMENT: review-${{ github.event.number }}
      run: |
        DISTRIBUTION_ID=$(aws cloudformation describe-stacks --stack-name applications-$CDK_DEPLOY_ENVIRONMENT | jq -r '.Stacks | .[] | .Outputs | reduce .[] as $i ({}; .[$i.OutputKey] = $i.OutputValue) | .DistributionId')
        aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"


  formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Install leptosfmt
        run: cargo install leptosfmt
      - name: Format check
        run: leptosfmt --check .

  comment-deployment-info:
    name: Comment Deployment Info
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    needs: 
      - deploy-review-environment
    steps:
      - uses: actions/github-script@v9
        env:
          PR_NUMBER: ${{ github.event.number }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const url = `https://review-${process.env.PR_NUMBER}.calculator.arithmico.com`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `**Review deployment created**: Click [here](${url})`
            });
