name: "Check Pull Request"
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo test --all-features
        shell: bash

  test-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: cargo-bins/cargo-binstall@main
    - shell: bash
      run: .github/workflows/setup.sh
    - uses: actions/setup-node@v6
      with:
        node-version: 22
    - name: setup e2e tests
      working-directory: packages/applications/arithmico-e2e
      run: |
        npm ci
        npx playwright install --with-deps
    
    - name: prebuild app
      working-directory: packages/applications/arithmico
      shell: bash
      run: |
        touch index.css 
        ~/.cargo/bin/trunk build
    
    - name: setup e2e tests
      working-directory: packages/applications/arithmico-e2e
      run: npx playwright test

  build-review-artifact:
    name: build review artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: cargo-bins/cargo-binstall@main
    - shell: bash
      run: .github/workflows/setup.sh
    - name: build
      working-directory: packages/applications/arithmico
      shell: bash
      run: |
        touch index.css 
        ~/.cargo/bin/trunk build --release
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        role-to-assume: ${{ secrets.CDK_ROLE_ARN }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ vars.AWS_REGION }}

    - name: upload artifact
      working-directory: packages/applications/arithmico/dist
      shell: bash
      env:
        BUCKET_NAME: ${{ vars.ARTIFACTS_BUCKET_NAME }}
      run:
        # use review-{pull-request-number} as artifact name
        ARTIFACT="review-${GITHUB_REF_NAME%/merge}";
        DEST_PATH="s3://$BUCKET_NAME/calculator/$ARTIFACT/main/web";
        aws s3 sync . $DEST_PATH --delete;

  test-infrastructure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        role-to-assume: ${{ secrets.CDK_ROLE_ARN }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ vars.AWS_REGION }}
    - name: CDK Synth
      working-directory: infrastructure
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: ${{ vars.AWS_REGION }}
        APP_VERSION: dev
      run: |
        npm ci
        npm run cdk -- synth -q

  formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Install leptosfmt
        run: cargo install leptosfmt
      - name: Format check
        run: leptosfmt --check .
