name: Cleanup Pull Request
on:
  pull_request:
    types: [closed]

permissions:
  id-token: write
  contents: read

jobs:
  remove-review-artifact:
    name: Delete Review Artifact
    runs-on: ubuntu-latest
    steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@6.2.2
      with:
        role-to-assume: ${{ secrets.CDK_ROLE_ARN }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ vars.AWS_REGION }}

    - name: Delete Artifact
      shell: bash
      env:
        BUCKET_NAME: ${{ vars.ARTIFACTS_BUCKET_NAME }}
        PR_NUMBER: ${{ github.event.number }}
      run:
        ARTIFACT="review-$PR_NUMBER";
        DEST_PATH="s3://$BUCKET_NAME/calculator/$ARTIFACT";
        aws s3 rm $DEST_PATH --recursive;
  
  undeploy-review-environment:
    name: Undeploy Review Environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version: 24
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@6.2.2
      with:
        role-to-assume: ${{ secrets.CDK_ROLE_ARN }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ vars.AWS_REGION }}
    - name: Install NPM Dependencies
      run: npm ci
    - name: CDK Destroy
      working-directory: infrastructure
      shell: bash
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: ${{ vars.AWS_REGION }}
        CDK_DEPLOY_ARTIFACT: review-${{ github.event.number }}
        CDK_DEPLOY_ENVIRONMENT: review-${{ github.event.number }}
      run: |
        mkdir -p ../packages/applications/arithmico/dist
        npm run cdk -- destroy --all --force
