name: Create Release
on:
  push:
    branches: 
      - main

permissions:
  contents: write
  id-token: write
  actions: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-24.04
    outputs:
      version_tag: ${{ steps.create-tag.outputs.version_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install create_version
        shell: bash
        run: cargo install --path packages/applications/create_version
      - name: Create and push tag
        id: create-tag
        shell: bash
        env: 
          SEMVER_PRERELEASE: ${{ vars.SEMVER_PRERELEASE }}
        run: |
          VERSION_TAG=$(create_version)
          git tag $VERSION_TAG
          git push origin $VERSION_TAG
          echo "version_tag=$VERSION_TAG" >> "$GITHUB_OUTPUT"
  
  deploy-infrastructure:
    name: Deploy Infrastructure
    concurrency:
      group: staging-environment
    runs-on: ubuntu-24.04
    needs: 
      - create-release
      - build-calculator
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: ${{ secrets.CDK_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}
      - name: CDK Deploy
        working-directory: infrastructure
        shell: bash
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          APP_VERSION: ${{ needs.create-release.outputs.version_tag }}
        run: |
          npm ci
          npm run cdk -- deploy --all --require-approval never
      - name: Create Cloudfront Invalidation
        shell: bash
        run: |
          DISTRIBUTION_ID=$(aws cloudformation describe-stacks --stack-name applications-main | jq -r '.Stacks | .[] | .Outputs | reduce .[] as $i ({}; .[$i.OutputKey] = $i.OutputValue) | .DistributionId')
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"

  build-calculator:
    name: Build Calculator
    runs-on: ubuntu-24.04
    needs: create-release
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - uses: cargo-bins/cargo-binstall@main
      - shell: bash
        run: .github/workflows/setup.sh
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: ${{ secrets.CDK_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: build calculator
        working-directory: packages/applications/arithmico
        shell: bash
        env:
          APP_VERSION: ${{ needs.create-release.outputs.version_tag }}
        run: |
          touch index.css 
          ~/.cargo/bin/trunk build --release
      - name: upload artifact
        working-directory: packages/applications/arithmico/dist
        shell: bash
        env:
          VERSION_TAG: ${{ needs.create-release.outputs.version_tag }}
          BUCKET_NAME: ${{ vars.ARTIFACTS_BUCKET_NAME }}
        run: |
          DEST_PATH="s3://$BUCKET_NAME/calculator/$VERSION_TAG/main/web"
          aws s3 sync . $DEST_PATH
