name: Create Release
on:
  push:
    branches: 
      - main

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-24.04
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install create_version
        shell: bash
        run: cargo install --path packages/applications/create_version
      - name: Create and push tag
        shell: bash
        env: 
          SEMVER_PRERELEASE: ${{ vars.SEMVER_PRERELEASE }}
        run: |
          VERSION_TAG=$(create_version)
          git tag $VERSION_TAG
          git push origin $VERSION_TAG
  
  deploy-infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-24.04
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.CDK_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: test cdk
        working-directory: infrastructure
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ env.AWS_REGION }}
        run: |
          npm ci
          npm run cdk -- deploy
