name: Create Release
on:
  push:
    branches: 
      - main

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-24.04
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install create_version
        shell: bash
        run: cargo install --path packages/applications/create_version
      - name: Create and push tag
        shell: bash
        env: 
            SEMVER_PRERELEASE: ${{ vars.SEMVER_PRERELEASE }}
        run: |
          VERSION_TAG=$(create_version)
          git tag $VERSION_TAG
          git push origin $VERSION_TAG
    


